### ISSUE TITLE
Feature request: Run for multiple sources

### ISSUE THREAD

**Issue by xpepermint** [RyuuGan/sol-merger#1]
Let me first thank you for publishing this package. I was just about to write one like this. I wrote a proposal to add the `combine` option to `truffle` yesterday. Today I found your package so I immediately publish a link to your package [there](https://github.com/trufflesuite/truffle/issues/564). Adding a pull request there would be great!

Usually I have multiple standalone contracts in my projects so what I would like to see is a more generic way for compiling them all in a single command. An option to run sol-merger command for multiple sources could look like this:

```
$ sol-merger ./contracts/MyContract.sol ./build/contracts/MyContract.sol
$ sol-merger ./contracts ./build/contracts
$ sol-merger ./contracts/*.sol ./build/contracts
$ sol-merger --append "_merged" ./contracts ./build/contracts
```

**Comment by RyuuGan** [comment]
Hello

This functionality is about to be implemented. So the first parameter will be a glob and the second is output directory (if missing then the same as contract) like the 3rd variant. 

I'll also think about append option.
