### ISSUE TITLE
import source file form packages failed  

### ISSUE THREAD

**Issue by ghost** [RyuuGan/sol-merger#10]
```
//this file is import from node_modules
import "chainlink/solidity/contracts/Chainlinked.sol";

//and in Chainlinked.sol also import another file form node_modules.
import "solidity-cborutils/contracts/CBOR.sol";
```
so build failed.
error message

Error: ENOENT: no such file or directory, stat '/Users/jarivs/Google Drive/Olympus/draft/protocol/node_modules/chainlink/node_modules/solidity-cborutils/contracts/CBOR.sol'

**Comment by RyuuGan** [comment]
Hello @Orangem21 ,

The main problem that I can't reproduce this issue because `chainlink` [npm package](http://npmjs.com/chainlink) does not contain any solidity contracts and repository is removed.

Best regards,
Valerii Aligorskii

**Comment by ghost** [comment]
```
npm install github:smartcontractkit/chainlink --save
import "chainlink/solidity/contracts/Chainlinked.sol";
```
thanks,

**Comment by RyuuGan** [comment]
Check the new version on `npm`. It should fix the issue.

**Comment by ghost** [comment]
```
nvm use 10.14
Now using node v10.14.2 (npm v6.4.1)
```
still error

**Comment by RyuuGan** [comment]
Can't reproduce with the latest version: 

```
"scripts": {
  "build-contracts": "sol-merger \"./contracts/*.sol\" ./build"
},
"dependencies": {
  "chainlink": "github:smartcontractkit/chainlink",
  "sol-merger": "^0.1.3"
}
```

contract: 

```
pragma solidity ^0.4.0;

import "chainlink/solidity/contracts/Chainlinked.sol";
```

**Comment by ghost** [comment]
OK, I make a mistake, I update the NPM version not the sol-merger version .
Thanks,  dev.
