### ISSUE TITLE
Keep the comments

### ISSUE THREAD

**Issue by katat** [RyuuGan/sol-merger#19]
Hi @RyuuGan,

The latest release is awesome! 
I have one request. Can we make it configurable to keep the comments?

Best regards,
Kata

**Comment by conlan** [comment]
Bumping this issue as I ran into it while using the truffle-plugin-verify package here: https://github.com/rkalis/truffle-plugin-verify. 

Would be great to have a way for comments to be preserved:

<img width="904" alt="Screen Shot 2019-11-26 at 12 25 10 AM" src="https://user-images.githubusercontent.com/79074/69611797-6e417d80-0fe3-11ea-8729-ad0a0f795499.png">7

<img width="668" alt="Screen Shot 2019-11-26 at 12 24 15 AM" src="https://user-images.githubusercontent.com/79074/69611743-51a54580-0fe3-11ea-8813-91d670faa235.png">

Thanks again for the awesome work: @RyuuGan

**Comment by RyuuGan** [comment]
Should be fixed in `1.2.0`

**Comment by rkalis** [comment]
@alsco77 reported an issue with comments preservation (https://github.com/rkalis/truffle-plugin-verify/issues/31). It appears that comments outside of contract definitions are not preserved.
