### ISSUE TITLE
Support circular dependencies

### ISSUE THREAD

**Issue by rkalis** [RyuuGan/sol-merger#27]
Several people reported issues with circular dependencies on truffle-plugin-verify ([#14](https://github.com/rkalis/truffle-plugin-verify/issues/14), [#17](https://github.com/rkalis/truffle-plugin-verify/issues/17)). It appears that sol-merger gets stuck in an infinite loop and runs out of memory eventually. @nklipa13 added a very small example that shows this in [truffle-plugin-verify#14](https://github.com/rkalis/truffle-plugin-verify/issues/14). I believe @ferittuncer also has more complex contract examples.

**Comment by rkalis** [comment]
It looks like it might still not completely work (at least for the repository I tested it with - [ethroulette](https://github.com/rkalis/ethroulette)).

Steps to reproduce:
```bash
git clone git@github.com:rkalis/ethroulette.git && cd ethroulette
npm i -g sol-merger@2.0.0
sol-merger "./contract/Roulette.sol"
```

It then gets stuck.

The repo has a UML diagram of the structure of the Roulette contracts, but basically `BackingContract` and `BackedToken` depend on each other, and `Roulette` extends `BackingContract`.

**Comment by RyuuGan** [comment]
@rkalis I found the issue and it is not about circular dependencies, so I'll fix it asap.

**Comment by rkalis** [comment]
Oh awesome! Thanks for looking into it. I'd just assumed it was due to circular dependencies. Thanks for fixing the issues!
