### ISSUE TITLE
OpenZeppelin contracts ERC-20 merge problem

### ISSUE THREAD

**Issue by dzarezenko** [RyuuGan/sol-merger#32]
I'm trying to merge my simple ERC-20 token contract code but one of the dependencies contracts sources is not in the result file.

My simple contract code: 
```
pragma solidity >=0.4.21 <0.7.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract MyToken is ERC20 {

  constructor() public ERC20("MyToken", "MyToken") {
    uint8 decimals = 6;
    uint256 initialSupply = 1000000;

    _setupDecimals(decimals);
    _mint(msg.sender, initialSupply * 10 ** uint256(decimals));
  }

}
```

Sol-merger command:
```
sol-merger -c "./contracts/AnyCashToken.sol" ./build/dist
```

In the result file, the `Address` contract source was not imported.

<img width="580" alt="Screenshot 2020-05-16 at 11 39 32" src="https://user-images.githubusercontent.com/148570/82115196-05ed8080-976a-11ea-943d-8bc97c0a7de3.png">

How can I merge my contracts in the right way?

**Comment by RyuuGan** [comment]
Hello, @dzarezenko 

Currently version `0.6` is not supported fully. Because there might be `structs` and other syntax that is not supported.

Currenlty I made a couple of pull requests to support latest solidity Grammar, but didn't receive any result. So I'll start looking on another solution.

To understand why it is an error, you can simply run next command:

```sh
DEBUG="sol-merger*" <command to parse contracts>
```

Connected issue: https://github.com/rkalis/truffle-plugin-verify/issues/30

Best regards,
Valerii Aligorskii

**Comment by RyuuGan** [comment]
Reminder for myself that this should also compile: 

https://github.com/sobolev-igor/test

https://github.com/rkalis/truffle-plugin-verify/issues/28

**Comment by RyuuGan** [comment]
Should be fixed in `v3.0.0`

**Comment by dzarezenko** [comment]
Thank you!

**Comment by Gideonsabat** [comment]
Hi, does anyone know how to merge openzeppelin contracts into a .sol file?

**Comment by RyuuGan** [comment]
Follow the installation guide: https://docs.openzeppelin.com/contracts/4.x/ and then use this library to merge it into one file.


Example of contract (with other library `zeppelin-solidity`): https://github.com/RyuuGan/sol-merger/blob/9d405a0ee771d661ff6804d3d6cb0f2b2d0c29de/test/contracts/MultiImports.sol#L3

You can checkout the readme file how to construct the build command.
