### ISSUE TITLE
SPDX license appears multiple times in merged files

### ISSUE THREAD

**Issue by Aniket-Engg** [RyuuGan/sol-merger#43]

**Comment by RyuuGan** [comment]
Hello @Aniket-Engg,

You can use [Post processing](https://github.com/RyuuGan/sol-merger#post-processing-support) to remove SPDX license: `SPDXLicenseRemovePlugin `.

Best regards,
Valerii Aligorskii

**Comment by Aniket-Engg** [comment]
Sure, thanks.
