### ISSUE TITLE
missing ';' at '{' error from unchecked syntax

### ISSUE THREAD

**Issue by jplew** [RyuuGan/sol-merger#48]
Hi, I'm trying to merge the following boilerplate OpenZeppelin contract:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract MyToken is ERC20 {
    constructor() ERC20("My Token", "MYTOKEN") {
        _mint(msg.sender, 1000000000000000000000);
    }
}
```

However it appears as though the `unchecked` control structure syntax (https://docs.soliditylang.org/en/v0.8.0/control-structures.html#checked-or-unchecked-arithmetic) raises the following errors: 

```
$ npx sol-merger MyToken.sol 
line 157:18 missing ';' at '{'
line 198:18 missing ';' at '{'
line 231:18 missing ';' at '{'
line 280:18 missing ';' at '{'
line 157:18 missing ';' at '{'
line 198:18 missing ';' at '{'
line 231:18 missing ';' at '{'
line 280:18 missing ';' at '{'
```

Line 157-159 look like this (https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L157): 

```
        unchecked {
            _approve(sender, _msgSender(), currentAllowance - amount);
        }
```

When I delete the unchecked lines it merged without a problem.

FYI `truffle-flattener` gives the same error.

**Comment by RyuuGan** [comment]
Hello,

Looks like you are using the new version of solidity which is currently not supported: 

```
pragma solidity ^0.8.0;
```

So maybe internal syntax compiler is not supporting this feature.

**Comment by jplew** [comment]
That makes sense, thanks for the quick reply. Which Solidity versions are presently supported, and are there plans to support the latest?

**Comment by RyuuGan** [comment]
Hello,

I'll try to add the newest version of contracts asap.

**Comment by jplew** [comment]
It might be as simple as bumping @solidity-parser/parser (or in your case `antlr4ts`) to the latest version: https://github.com/nomiclabs/truffle-flattener/pull/81

That change for me with `truffle-flattener`

**Comment by omar-saadoun** [comment]
Hello @RyuuGan ! Happens to me too, have you being able to work on this? Really appreciate. Thanks!

**Comment by Hashflower** [comment]
Need help on that one too, will save me MUCH time....

**Comment by RyuuGan** [comment]
Hello everyone,

Working on supporting new grammar.

**Comment by ctindogaru** [comment]
Having the same issues as well... What's the progress on this?

**Comment by juanmosv** [comment]
+1

**Comment by RyuuGan** [comment]
Hello,

This [PR](https://github.com/RyuuGan/sol-merger/pull/50) should fix the issue.

It will be merged this or next week.

Best regards,
Valerii Aligorskii

**Comment by RyuuGan** [comment]
Hi everyone,

Thank you for your patience.

`sol-merger@4.0.0` is avaiable in [npm](https://www.npmjs.com/package/sol-merger/v/4.0.0).

Closing the issue since it should be resolved.

Best regards,
Valerii Aligorskii
