### ISSUE TITLE
Recursive Node Module Resolution

### ISSUE THREAD

**Issue by trajan0x** [RyuuGan/sol-merger#58]
If this is setup in a lerna repo/yarn workspaces and modules are not [hoisted](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/), `node_modules` is not resolved correctly. `node_module` resolution should be recursive

I might make a PR around this, but is there any other kinds of external deps I should be considering? `dapp-tools`?

**Comment by RyuuGan** [comment]
Hello,

Can you create an example repo so I can take a look into this ?

Best regards,
Valerii Aligorskii

**Comment by RyuuGan** [comment]
Hi,

Can you say which version of `npm` do you run on the machine ?

Best regards,
Valerii Aligorskii

**Comment by trajan0x** [comment]
Hi,

We got around this by using `forge flatten` (synapsecns/sanguine#632) so this is fine as closed, but will add details here in case anyone is curious. This was commit prior to that change: https://github.com/synapsecns/sanguine/blob/ddf52a5eeb9f61ec22c7cedb5d68e281dc8af4b5

Node Version: v16.14.0
Nohoist workaround: https://github.com/synapsecns/sanguine/blob/ddf52a5eeb9f61ec22c7cedb5d68e281dc8af4b5/package.json#L10-L14
Yarn Version: yarn 1.22

TY
