### ISSUE TITLE
Issue merge contracts in Windows 7 with "build-contracts": "sol-merger './contracts/*.sol' ./build"

### ISSUE THREAD

**Issue by SergZen** [RyuuGan/sol-merger#9]
I have a message "No files found for merge" after "npm run-script build-contracts".

I have fixed this issues:
   "build-contracts": "sol-merger \\"./contracts/*.sol\\" ./build"

**Comment by RyuuGan** [comment]
Hello, @SergZen .

Yeap, Looks like on Windows you have to put quotes instead of single quotes.

Have fixed this at GitHub Readme file.

Best Regards, 
Valery Aligorksy.
